### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by mard1m** [oleksandrblazhko/ai-211-martinyuk#23]
### Завдання 1

1. Чистота повітря навколишнього середовища

2.
Обґрунтування:

Доступність -  складно самостійно забезпечити відповідну чистоту повітря навколишнього середовища без підтримки або додаткових приладів.

Зрозумілість - не є проблемою, так як для спостереження за чистотою навколишнього середовища не треба високої кваліфікації та із допомогою інтернету не возникне ніяких питань.

Цінність - інформація про чистоту навколишнього середовища має важливе значення для здоров'я, безпеки та комфорту людини. Із допомогою інтернету, я вважаю, отримання інформації коштує не дорого.

Актуальність - оскільки якість повітря може змінюватися з часом через різні фактори, такі як погодні умови або промислова діяльність, споживач повинен мати доступ до актуальних даних про чистоту повітря, щоб забезпечити найвищий рівень безпеки та надійності своїх досліджень.

### Завдання 2

1. Мета: Надати пояснення важливості покращення чистоти повітря навколишнього середовища для фінансової стабільності при читанні літературної поезії про самоповагу.

2.
Feature 1: Аналіз ринку фінансів
Знайомство з фінансовим ринком дозволить користувачеві отримати знання стосовно підтримання гарної стабільності для фінансів , які для нього важливі. 

Feature 2: Надсилати сповіщення про чистоти навколишнього середовища
 За допомогою сповіщень, користувач розуміє як змінюється чистота повітря з часом та допомогає у фінансової стабільності 
 Сповіщення зробленні для зручності, для того щоб залишатися поінформованим та для прискорення результата.

Feature 3: Авторизація користувача
Доступ до особистого облікового запису дозволить користувачеві зберігати та обробляти особисту інформацію, інформацію стосовно чистоти, які допоможуть йому досягти даної мети, створити свої налаштування, переглянути список обладнання, яке йому буде потрібно і т.п.

**Comment by oleksandrblazhko** [comment]
Завдання 1: обґрунтуйте ваш вибір інформаційних умов, вказавши по одному реченню, чому для цих
умов забезпечено інформаційну задоволеність і вам не потрібно було нічого записувати у
відповідній комірці таблиці під час виконання лабораторної роботи (не плутати із задоволеністю
реальною потребою).
Ось ваш аналіз - https://github.com/oleksandrblazhko/ai-211-martinyuk/tree/main/1-SoftwareRequirements/1.2-BusinessRequirementsForSoftware/1.2.1-AnalysisOfInformationNeeds
Доступність була проблемою, тому не треба її описувати.

Завдання 2: обґрунтуйте для трьох прецедентів той факт, що результати їх роботи дійсно наближають
користувача вашого програмного продукту до досягнення вказаної раніше мети.

Оцінка = 3 бали.

**Comment by oleksandrblazhko** [comment]
Продовжуйт працювати над КР2.
