### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by mard1m** [oleksandrblazhko/ai-211-martinyuk#24]
### Завдання 4
Обгрунтуйте ваш вибір моделі, визначивши її переваги під час створення схеми даних;
вкажіть якийсь виявлений недолік процесу проектування у порівнянні з моделлю даних, яку ви не обрали.

1.
Переваги:
Структурованість та нормалізація.
Просте налаштування та використовування.
Транзакційність та надійність.
Висока швидкість команд.

2.
Недоліки:
Не підтримує обмеження Check SQL.
Функція GROUP BY не завжди працює так, як очікується.

**Comment by oleksandrblazhko** [comment]
Треба виконати завдання 1

**Comment by oleksandrblazhko** [comment]
Завдання1 - З урахуванням вище вказаного ще раз розгляньте будь-які три функціональні вимоги
нижнього рівня, наприклад, FR1.1, FR2.1, FR2.2, та в якості експерименту змініть їх опис так, щоб:
-  перша вимога перестала відповідати умові «атомарність»;
- друга вимога перестала відповідати умові «завершеність»;
- третя вимога перестала відповідати умові «безкоштовність реалізації».

**Comment by oleksandrblazhko** [comment]
Треба зробити також - 
Завдання 2 (1 бал)
У лабораторній роботі No4 вами надано концептуальний опис архітектури програмного
продукту (файл 1.5.1-SoftwareArchitectConcept/README.md) та оцінку трудомісткості процесу
розробки програмного продукту (каталог 1.5.2-UCPEstimationSize/). З урахуванням вище вказаного:
1) обгрунтуйте визначення показника технічної складності проекту ««Розподілена система»
з урахуванням розподіленності компонент в концептуальному описі архітектури програмного
продукту;
2) обгрунтуйте визначення показника технічної складності проекту «Спеціальні вимоги до
навчання користувачів» з урахуванням особливостей акторів програмного продукту.

**Comment by mard1m** [comment]
### Завдання 1
FR      |     Опис функціональної вимоги    |
|--------|--------------------------------|
|       FR1    |    Отримувати дані в зручному для користувача форматі|
|      FR1.1   |   Система дозволяє переглядати інформацію про споживання у часовому проміжку|
|      FR1.2   |   Система дозволяє порівнювати споживання на довгіх проміжках|


Зміна атомарності: FR1:
Змінена вимога: “Отримувати дані в зручному для користувача форматі та коригувати за налищтуванням”
Ця вимога тепер не є атомарною, оскільки вона включає у собі декілька дій.

Зміна завершеності: FR1.1
Змінена вимога: “Система дозволяє переглядати інформацію  у часовому проміжку”
Ця вимога тепер не є завершеною, оскільки не зрозуміло, яку інформацію повинна система переглядати.

Зміна безкоштовності реалізації: FR1.2:
Змінена вимога: “Система дозволяє порівнювати споживання на довгіх проміжках, обравши критерії порівняння у пошуковій системі”
Ця вимога тепер залежить від особливостей подальшої реалізації, оскільки описано конкретний спосіб взаємодії користувача з програмним продуктом.

**Comment by mard1m** [comment]
### Завдання 2

|Показник    |     Опис показника    |   Вага_i  |         STi       |       STi * Вага_i
|--------|--------------------------------|-----|---------|---------|
|       T1   |    Розподілена система| 2  |    3    |  6    |
|      T13  |   Система дозволяє переглядати інформацію про споживання у часовому проміжку|  1 |    1    |  1   |

Розподілена система:
Мобільний додаток для користувачів вимагає розробки інтерфейсів для взаємодії з веб-сервісом та передачі даних між ними. Це призводить до складнішого процесу розробки та тестування.
Веб-сервіс для обробки даних вимагає надійної синхронізації з мобільним додатком та сервером бази даних, що збільшує технічну складність проекту.
Сервер бази даних потребує високого рівня безпеки та надійності для збереження даних, що впливає на технічну складність.
Базове значення 2 відображає стандартну складність розробки програмного продукту, а множник складності 3 підкреслює, що розподіленість системи істотно збільшує цю складність. Таким чином, загальне значення технічної складності 6 відображає високий рівень складності.

Спеціальні вимоги до навчання користувачів:
З огляду на різноманітну аудиторію користувачів, важливо надати спеціальні функції для навчання користувачів, такі як покрокові інструкції та навчальні модулі.
Ці функції вимагають додаткових ресурсів для розробки та підтримки, що підвищує технічну складність проекту.
Отже, на основі цих обгрунтувань можна визначити показники технічної складності для проекту "Розподілена система" та "Спеціальні вимоги до навчання користувачів" як високі.
Базове значення 1 та множник складності 1 показують, що ПП не потребує спеціальних вимог для навчання користувачів.

**Comment by oleksandrblazhko** [comment]
Оцінка = 2 бали
